# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

variables:
  buildConfiguration: 'Release'
  serviceConnectionBase: 'AccountingProject'

stages:
# Build the project and run commands (e.g. unit tests) 
# that don't require a deployed application
- template: build.yml
  parameters:
    buildConfiguration: ${{ variables.buildConfiguration }}

# Deploy to the Sandbox environment and run commands (e.g. migrations) that 
# do require a provisioned and/or deployed application
- stage: 'Sandbox'
  displayName: 'Deploy to Sandbox'
  dependsOn: Build

  jobs:
  - template: deploy.yml
    parameters:
      # The Service Connection is named the same as the Resource Group
      # the deployment will target so this parameter serves to specify both
      ServiceConnection: ${{ variables.ServiceConnectionBase }}Sandbox
      BuildConfiguration: ${{ variables.buildConfiguration }}
      EnvironmentName: Sandbox



